### PR TITLE
run regtests at test stage

### LINKED ISSUE #20: switch regtests to test stage
currently, regtests are running at build stage

### PR DESCRIPTION
**Pull request by ltalirz**
Fix #20 

We've been running the regtests at the build stage for convenience.
However, this means we are not testing the executable in the environment
that would be seen by a user installing the package.

It is therefore important to move the regtests to the "test" stage.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@dev-zero 
We're currently running tests at the "build" stage, which prevents us from catching issues with missing runtime dependencies (e.g. we just realized that `scalapack` was missing).

Can I run the regtests on the cp2k executable installed by conda; without all the folder structure that is created by building a new executable?
(or can I easily "fake" this folder structure?)

If one just runs `make test`, it says `make: *** No rule to make target `test'.  Stop.`

**Comment by dev-zero** [comment]
`make test` is a wrapper around `tools/regtesting/do_regtest` which in turn can again call `make` again (convoluted, yes).
But with the right parameters you should be able to call `tools/regtesting/do_regtest` with an already present executable and avoid that `do_regtest` calls into `make` again, afaik.
Please note that a missing `scalapack` would not necessarily have been cought by that since the `do_regtest` asks the `cp2k` exe for the flags it has been built and if the filtering is properly set the tests for that feature won't be run. So, you can not ask for tests for a specific feature to be run. That being said, running mpi-enabled tests without scalapack would have most likely failed since it is not supported (but also not explicitly tested for, maybe submit a PR with `#ifdef __parallel #ifndef _SCALAPACK #error "uh, oh"` ...?)`.

**Comment by ltalirz** [comment]
Thanks @dev-zero !

> But with the right parameters you should be able to call tools/regtesting/do_regtest with an already present executable and avoid that do_regtest calls into make again, afaik.

Is there some documentation I can read on how to do this?

> Please note that a missing scalapack would not necessarily have been cought by that since the do_regtest asks the cp2k exe for the flags it has been built and if the filtering is properly set the tests for that feature won't be run. So, you can not ask for tests for a specific feature to be run.

Ok, that should not a problem then. Before, the MPI tests were run successfully and scalapack *was* present in the build environment (listed under `host`). It was just not listed as a dependency under `run`, which resulted in it not being installed as a dependency together with the cp2k package.
(for some reason, all the other libraries so far have been added as a dependency without me listing them explicitly under `run` - something to figure out later).

**Comment by dev-zero** [comment]
only what `tools/regtesting/do_regtest --help` gives you, I am afraid.
And it seems you have to put the cp2k.exe inside a dir `exe/.../` subdirectory to run the tests since this is somewhat hardcoded. But with `-arch` you can determine the name of the subdir.

**Comment by ltalirz** [comment]
Hm... I just realised that the [conda-forge docs say](https://conda-forge.org/docs/maintainer/adding_pkgs.html#tests-outside-of-the-package)
> Note that conda-build runs the tests in an isolated environment after installing the package – thus, at this point it does not have access to the original source tarball. This is to ensure that the test environment is as close as possible to what an end-user will see.
> This makes it very hard to run tests that are not installed with the package.

That indeed makes it hard :-D

In that case I will drop this attempt.

**Pull request closed without merging**
