### PR TITLE
cp2k 8.1

### PR DESCRIPTION
**Pull request by ltalirz**
* reset build number
 * remove sopt symlink (only OpenMP versions for cp2k 8.1)
 * remove regtest patch (incorporated in cp2k source code)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@dev-zero @oschuett 
For some reason cp2k 8.1 is ignoring the `FC` environment variable on the serial (openmp) builds and tries to use `mpif90` instead (that isn't installed), see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=303559&view=logs&j=cc7f06b8-47bb-5f80-5e0d-1224ea213530&t=1c90cc3e-b00e-5eab-82a4-21c378b43900&l=210).
It only works if I set the `FC` variable in the archfile explicitly (which I don't want to do, since the path/name of the serial compiler may change as conda environments evolve).

Any ideas why this happens?

The original archfiles without explicit `FC` worked fine with cp2k 7.1

**Comment by dev-zero** [comment]
My guess is that this is due to the explicit assignment of several variables in DBCSRs Makefile which gets included by CP2K:

https://github.com/cp2k/dbcsr/blob/master/.cp2k/Makefile

Explicit assignment overrides the value of variables imported from the environment.

On 14 April 2021 10:10:32 CEST, Leopold Talirz ***@***.***> wrote:
***@***.*** @oschuett

**Comment by ltalirz** [comment]
Thanks @dev-zero , looks to me like you're right - these defaults were added 13 months ago https://github.com/cp2k/dbcsr/blame/master/.cp2k/Makefile

I guess we should open an issue for this. should this go to cp2k or dbscr?

**Comment by dev-zero** [comment]
@ltalirz to DBCSR since it should be fixed there (either by removing them or replacing them with `?=`). Thanks!

**Comment by ltalirz** [comment]
@oschuett 
On the OSX build I'm running into [errors](
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=303579&view=logs&j=65769002-1136-5bbb-5e91-b3fbb7cdd70e&t=fdb86174-6733-5ed6-1dd5-f2594c29f582&l=460
) related to the usage of `clock_gettime` and the undeclared `CLOCK_PROCESS_CPUTIME_ID` symbol:

```
x86_64-apple-darwin13.4.0-clang -c -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cp2k-8.1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fopenmp -std=gnu99 -fopenmp -std=gnu99 $SRC_DIR/src/grid/grid_replay.c
/Users/runner/miniforge3/conda-bld/cp2k_1618390734638/work/src/grid/grid_replay.c:345:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]

    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &start_time);
    ^
/Users/runner/miniforge3/conda-bld/cp2k_1618390734638/work/src/grid/grid_replay.c:345:19: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &start_time);
                  ^
/Users/runner/miniforge3/conda-bld/cp2k_1618390734638/work/src/grid/grid_replay.c:371:19: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &end_time);
                  ^
/Users/runner/miniforge3/conda-bld/cp2k_1618390734638/work/src/grid/grid_replay.c:378:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &start_time);
    ^
/Users/runner/miniforge3/conda-bld/cp2k_1618390734638/work/src/grid/grid_replay.c:378:19: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &start_time);
                  ^
/Users/runner/miniforge3/conda-bld/cp2k_1618390734638/work/src/grid/grid_replay.c:406:19: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &end_time)
```

As you can see from the compilation line I've already added `-std=gnu99`, which I thought might solve this but apparently it didn't.

I'm a little confused as the [Darwin archfiles for cp2k](https://github.com/cp2k/cp2k/blob/master/arch/Darwin-gfortran.psmp) added by @fxcoudert seem to work fine for him but I guess that's because they are using gcc rather than clang (?). Is this some difference between clang's `std=gnu99` and gcc's `std=gnu99`?

P.S. For reference, the relevant lines in the archfile are
```
FC          = x86_64-apple-darwin13.4.0-gfortran
CPP         = $(CC)-cpp
CPPFLAGS   += -C -P -traditional -D__NO_IPI_DRIVER -nostdinc
# default -std=c99 complains about missing declaration of clock_gettime
CFLAGS     += -fopenmp -std=gnu99
```

P.P.S. As a reminder, we're using clang because it's the default C compiler for osx on conda-forge. See also comment by @dev-zero https://github.com/conda-forge/cp2k-feedstock/pull/7#issuecomment-737241091

**Comment by ltalirz** [comment]
For reference, the linux builds run through fine, including the regtests

linux ssmp
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2849
Total number of   tests 2849
```

linux psmp
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2900
Total number of   tests 2900
```

**Comment by dev-zero** [comment]
You should not have to use `gnu99`, but rather `c11`.

**Comment by dev-zero** [comment]
also, I was able to build CP2K with clang on a recent OSX, so it should work in principle, but not necessarily v8.1 since there we still had some issues with `memalign`.

**Comment by dev-zero** [comment]
[stackoverflow](https://stackoverflow.com/a/39801564/1400465) says Sierra, so darwin-13 should have it.

**Comment by dev-zero** [comment]
sorry, no idea what else it could be atm

**Comment by oschuett** [comment]
@ltalirz, AFAIK the `clock_gettime` routine is part of the POSIX standard. However, for gclib I had to set the [_XOPEN_SOURCE](https://github.com/cp2k/cp2k/blob/master/src/grid/grid_replay.c#L9) macro to enable it. Maybe on OSX it has a different name?

**Comment by ltalirz** [comment]
Looking at the [cpython configure source code](https://github.com/python/cpython/blob/c4073a24f95b54705416138dc1f20141ad76dd37/configure#L3830-L3840), it seems to me like `_XOPEN_SOURCE` is disabled there for all darwin kernels from 6.x onwards (can someone confirm that I'm reading this correctly?).
I believe we are [running Darwin 19.6.0 here](https://github.com/actions/virtual-environments/blob/macOS-10.15/20210412.2/images/macos/macos-10.15-Readme.md).

At the same time, they [`#define _DARWIN_C_SOURCE 1` in order to re-enable stuff that would be disabled by `_XOPEN_SOURCE`](https://github.com/python/cpython/blob/c4073a24f95b54705416138dc1f20141ad76dd37/configure#L3440-L3444). 
Not sure whether that is still needed if we remove the `_XOPEN_SOURCE` macro on the osx build, but perhaps it won't hurt?

**Comment by ltalirz** [comment]
Ok, it seems one needs to tell conda that the target platform is OSX>=10.12 (which does make sense).
https://github.com/conda-forge/staged-recipes/pull/14079#issuecomment-789847082

**Comment by oschuett** [comment]
I seems we could also use `_POSIX_C_SOURCE` [instead](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html). I'm not sure if this helps with OSX, but it certainly has a more self-explanatory name.

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by dev-zero** [comment]
@ltalirz and now it fails at the osx error we already know about and which was fixed (multiple times) in the meantime

**Comment by ltalirz** [comment]
> @ltalirz and now it fails at the osx error we already know about and which was fixed (multiple times) in the meantime

Ok, you mean fixed in the cp2k source code?

What is the right approach here in your opinion:
 1. Add a patch for it here
 2. Exclude MacOS from the cp2k 8.1 conda package

**Comment by dev-zero** [comment]
Yes, fixed in CP2K.
Since the final fix is mixed up with with other changes in the grid code by now someone would have to backport it. So, exclude and wait for 8.2 (scheduled for End of April or Mid May).

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
Note: https://github.com/conda-forge/cp2k-feedstock/pull/27 will need to be merged before this one.

**Comment by ltalirz** [comment]
linux ssmp
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2849
Total number of   tests 2849
```

linux psmp
```
Number of FAILED  tests 0
Number of WRONG   tests 1
Number of CORRECT tests 2899
Total number of   tests 2900
```

The one wrong test is
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/Linux-x86-64-conda/psmp/TEST-Linux-x86-64-conda-psmp-2021-04-14_16-41-00/QS/regtest-gpw-2-3/hcn_meta_chaincoord.inp.out : 
 Total energy: : ref = -16.64019903493714 new = -16.64019903493535  
 relative error :   1.07604945e-13 >  numerical tolerance = 1e-13  
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I'll have a look whether this tolerance is already adjusted - in any case, this seems acceptable.

**Pull request merged**
