### PR TITLE
v2022.1

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by oschuett** [comment]
Note that we just released version [2023.1](https://github.com/cp2k/cp2k/releases/tag/v2023.1).

**Comment by ltalirz** [comment]
Sure - the last release on the feedstock is 9.1, since the PR bot stopped opening PRs (likely since there was a subtle change in the download URL for the tarball when switching to calendar versioning).

Happy to skip the two versions in between then and 2023.1...

For the record, the test suite fails because 7 tests are now timing out
```
------------------------------- Errors ---------------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/xTB/regtest-5/AdeThyvdW.inp.out


Timed out after 400.0142158350002 seconds.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/SE/regtest-3-2/N3-rp_colvar.inp.out


Timed out after 400.015185018 seconds.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/SE/regtest-3-2/LM-KSDO-D.inp.out


Timed out after 400.0059543749994 seconds.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/SE/regtest-3-4/N3_rp_md.inp.out


Timed out after 400.01403188899985 seconds.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/SE/regtest-3-4/N3_dp_md.inp.out


Timed out after 400.0136339270002 seconds.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/SE/regtest-3-4/N3_rp_dp_md.inp.out


Timed out after 400.0153178439996 seconds.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/TEST-Linux-x86-64-conda-ssmp-2023-01-18_02-44-58/SE/regtest/geom.inp.out


Timed out after 400.0115399039987 seconds.
```

**Comment by oschuett** [comment]
> Happy to skip the two versions in between then and 2023.1...

Yeah, I think there is no harm in skipping ahead.

> For the record, the test suite fails because 7 tests are now timing out

We're working on it: https://github.com/cp2k/cp2k/pull/2507, https://github.com/cp2k/cp2k/pull/2512

In the future we could also consider to use the new `--smoketest` feature (https://github.com/cp2k/cp2k/pull/2501).

So testing should get easier once these changes are release in a couple of months.

**Comment by ltalirz** [comment]
For 2023.1 should there be anything stopping us from using the cmake route here on conda-forge?

**Comment by oschuett** [comment]
> For 2023.1 should there be anything stopping us from using the cmake route here on conda-forge?

No, please give cmake a try.

**Comment by ArtemFediai** [comment]
Hello, it has been a while since this pull request. Could I kindly get an update on the status of the CP2K 2023.1 Conda package? Thanks a lot!

**Comment by ltalirz** [comment]
It's been on my todo list for a long time but so far it always got bumped - feel free to move ahead with a PR yourself if you have time!

**Pull request closed without merging**
