### PR TITLE
cp2k v8.2.0

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
If you need access to https://github.com/conda-forge/libxc-feedstock just ping me.

**Comment by ltalirz** [comment]
Will need to wait until https://github.com/conda-forge/libxc-feedstock/pull/8 is merged

**Comment by loriab** [comment]
I'm glad to hear you're interested in conda-forge/libxc-feedstock#8 . I've built trial versions of v5.1 over at staged-recipes and uploaded them at https://anaconda.org/psi4/libxc/files?version=5.1.0rc2, so if you need to do any testing before libxc and the cmake recipe are finalized, grab them from `-c psi4/label/trial`.

**Comment by ltalirz** [comment]
@loriab Thanks for the update!

When trying to compile against libxc 5.1, I'm now getting type mismatch errors on integer length
```

 1656 |                   CALL xc_f03_lda_exc(xc_func, 1, rhov(1, 1), exc)
      |                                                                  1
Error: Type mismatch in argument 'np' at (1); passed INTEGER(4) to INTEGER(8)
/home/conda/feedstock_root/build_artifacts/cp2k_1611087792921/work/src/xc/xc_libxc.F:1669:73:
```

I have too little understanding of whether this a compiler issue / issue on cp2k side - do you happen to know?
@dev-zero is there a special `D__` flag for libxc version 5.1?

**Comment by dev-zero** [comment]
we will no support libxc-5.0 and libxc-5.1 just got released, no, there is no special flag, at the moment you have to use libxc-4.3.x

**Comment by dev-zero** [comment]
@fstein93 will probably update https://github.com/cp2k/cp2k/pull/914 as soon as he has time

**Comment by ltalirz** [comment]
thanks, I just came across this as well.

> at the moment you have to use libxc-4.3.x

Since this libxc version is not available for macos on conda-forge, libxc support on conda-forge will need to wait until the next cp2k release - I'll rebase this PR then, no problem.

**Comment by jan-janssen** [comment]
I just released libxc 5.1.3 on conda https://github.com/conda-forge/libxc-feedstock/pull/13 and at least 5.1 https://github.com/cp2k/cp2k/pull/914 and 5.1.2 https://github.com/cp2k/cp2k/pull/1389 are supported by cp2k. So once we are able to build 8.1.0 https://github.com/conda-forge/cp2k-feedstock/pull/10 then we should be able to continue with the libxc integration.

**Comment by fstein93** [comment]
CP2K is supporting 5.1.3 now. cp2k/cp2k#1447

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
test results ssmp
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2911
Total number of   tests 2911
GREPME 0 0 2911 0 2911 X
```

test results psmp
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2962
Total number of   tests 2962
GREPME 0 0 2962 0 2962 X
```

Good to go!

**Comment by oschuett** [comment]
Wohoo! Record time :-)

**Pull request merged**
