### PR TITLE
Add libxsmm

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
Somehow the addition of libxsmm caused an insatisfiable dependency for OSX:
```
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {"libgfortran[version='>=3.0,<4.0.0.a0']", "libblas[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0.*|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0.*',build='4_openblas|4_mkl|5_blis|6_blis|6_openblas|7_mkl|8_blis|8_mkl|9_openblas|9_mkl|12_blis|12_openblas|13_blis|13_openblas|14_blis|14_mkl|14_openblas|15_blis|20_mkl|0_blis|0_openblas|1_blis|2_blis|3_blis|3_openblas|4_openblas|5_blis|6_blis|6_mkl|7_mkl|7_blis|7_openblas|6_openblas|5_mkl|5_openblas|4_mkl|4_blis|2_openblas|1_openblas|21_mkl|19_mkl|18_mkl|17_openblas|16_mkl|16_blis|16_openblas|15_mkl|15_openblas|13_mkl|12_mkl|11_openblas|11_mkl|11_blis|10_mkl|10_openblas|10_blis|9_blis|8_openblas|7_openblas|7_blis|6_mkl|5_mkl|5_openblas|4_blis']", 'libgfortran4', "libcxx[version='>=10.0.1|>=11.0.0|>=4.0.1|>=9.0.0|>=9.0.1']", "libgfortran[version='4.*|5.*']", 'libblas=3.8.0', "libgfortran[version='4.*|5.*|>=4.0.0,<5.0.0.a0|>=3.0.1,<4.0.0.a0']", "llvm-openmp[version='>=10.0.1|>=8.0.0']", "liblapack[version='>=3.8.0,<4.0.0a0']", "llvm-openmp[version='>=10.0.1|>=8.0.0|>=8.0.1']", "libcxx[version='>=4.0.1|>=9.0.1']", "libgfortran[version='>=3.0.1,<4.0.0.a0|>=4.0.0,<5.0.0.a0']", "libgfortran5[version='>=9.3.0']", "liblapack[version='3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0.*|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.8.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0|3.9.0.*',build='6_mkl|7_mkl|8_openblas|8_mkl|9_openblas|9_mkl|10_openblas|10_mkl|11_mkl|11_openblas|14_mkl|18_mkl|19_mkl|20_mkl|0_openblas|3_openblas|4_openblas|6_openblas|6_mkl|7_mkl|7_openblas|5_mkl|5_openblas|4_mkl|2_openblas|1_openblas|21_mkl|17_openblas|16_mkl|16_openblas|15_mkl|15_openblas|14_openblas|13_mkl|13_openblas|12_openblas|12_mkl|7_openblas|6_openblas|5_mkl|5_openblas|4_mkl|4_openblas']", 'libgfortran5', "libgfortran4[version='>=7.5.0']", "llvm-openmp[version='>=8.0.0|>=8.0.1']", "libcxx[version='>=4.0.1']", "llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=4.0.1|>=9.0.0|>=8.0.1|>=8.0.0']", "libblas[version='>=3.8.0,<4.0a0']"}
```

I notice that "Remove Mac OS X support" because "Mac builds randomly crash" in the [commits of the libxsmm feedstock](https://github.com/conda-forge/libxsmm-feedstock/commits/master)  - but there definitely still are (slightly outdated) osx builds. Perhaps none of them are compatible with state-of-the-art compilers?

**Comment by ltalirz** [comment]
The linux build complains
```
Fatal Error: Cannot open module file 'libxsmm.mod' for reading at (1): No such file or directory
```
However, [downloading](https://anaconda.org/conda-forge/libxsmm/1.16.1/download/linux-64/libxsmm-1.16.1-h509447c_1.tar.bz2) and inspecting the conda-forge libxsmm package, both `libxsmm.mod` and `libxsmmf.so` are there.

The fortran compiler flags include `-isystem $PREFIX/include` , which seems to have worked for all other includes so far.
Does one need to add `-I $PREFIX/include` separately?

**Comment by jan-janssen** [comment]
If you need access to https://github.com/conda-forge/libxsmm-feedstock just ping me.

**Comment by ltalirz** [comment]
Will need to wait until https://github.com/conda-forge/libxsmm-feedstock/issues/12 is resolved

**Comment by jan-janssen** [comment]
The updated package is now uploaded to anaconda https://anaconda.org/conda-forge/libxsmm/files - it should be available in 30-45min. Then we can restart the build.

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@jan-janssen Any ideas why it decided to stop running the builds?
Should I try to force-push again?

**Comment by jan-janssen** [comment]
> @jan-janssen Any ideas why it decided to stop running the builds?
> Should I try to force-push again?

At least they worked before you increased the build number https://github.com/conda-forge/cp2k-feedstock/runs/1736043243

**Comment by jan-janssen** [comment]
@conda-forge-admin restart ci

**Review by jan-janssen — APPROVED** [review]
The tests passed so from my perspective the pull request is ready to merge.

**Comment by ltalirz** [comment]
Yep, and not only via CI but also the regtests (until https://github.com/cp2k/cp2k/issues/1299 is fixed we still have to check manually)

**Pull request merged**
