### PR TITLE
switch to openmp version

### PR DESCRIPTION
**Pull request by ltalirz**
can re-enable sopt version if we see this works

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Maybe it helps to explicitly add openmp in the dependencies https://conda-forge.org/docs/maintainer/knowledge_base.html#openmp

**Comment by ltalirz** [comment]
thanks for the hint, let's see whether this fixes the linux build :-)

a bit weird though that the osx build passes but not the linux one, while the documentation says that openmp is enabled on linux but not on osx.

In any case, we may still need to enable openmp also for the other compilers as mentioned by @dev-zero  (?)

I'm not quite sure though whether we will get into trouble with the clang / gfortran mix on osx then?
I.e. can we mix `-fopenmp=libomp` for C/C++ with `-lgomp` at the linking stage? Maybe [not](https://stackoverflow.com/a/33400688/1069467)?

**Comment by ltalirz** [comment]
@jan-janssen It seems to me that the linux environment is missing the `LDFLAGS_LD` environment variable (available on osx), which contains the linker flags in a form that can be passed to `ld` directly (i.e. without the `-Wl,` prefixes that are present in the `LDFLAGS` variable) .

So, I thought I'd be clever and simply use `gcc` as the linker on linux, but now I'm getting undefined references for gfortran objects - despite the fact that I still append `-lgfortran` to the `LDFLAGS`.

Any ideas what might be the problem here?

**Comment by ltalirz** [comment]
Hm, perhaps switching to `gcc` results in the `LDFLAGS` not being used at all at the linking stage (?)
That seems a bit weird though; I thought this bit was handled by the cp2k [makefile](https://github.com/cp2k/cp2k/blob/master/Makefile) rather than automatically via the binary (I might be wrong).

**Comment by ltalirz** [comment]
@jan-janssen any wisdom here?

**Comment by jan-janssen** [comment]
@ltalirz It is on my list, still I am not sure I can work on it before Christmas

**Comment by jan-janssen** [comment]
```
undefined reference to `_gfortran_stop_string'
```
Sounds like a lapack issue

**Comment by ltalirz** [comment]
@oschuett I thought I was done, but then I realized that the `build.sh` is missing `set -e` and [one test](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=254808&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=8563) fails on the osx build with clang.

It fails consistently in the osx openmp build, but it did not fail in the [sopt build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=247646&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=8492) that is in master.

The test is `QS/regtest-pao-2/H2O_pao_exp_cluster_sp.inp.out` and it fails with `Program received signal SIGABRT: Process abort signal`.

In commit https://github.com/conda-forge/cp2k-feedstock/pull/8/commits/70cf624d9d5d6860b5fcf9a50534cc24d25c8719 it fails at a different, later stage of the calculation, which makes me suspect that this is an out of memory issue (?).
Does this sound reasonable?

Are there ways to exclude tests from the regtest?
Should we try something like `ulimit -s unlimited`?

In general, is there a suitable subset of regtests that should be run here on conda-forge in order to guard against miscompilation issues, or should we aim to run the full set of regtests?

**Comment by dev-zero** [comment]
@ltalirz due to the complexity of CP2K and the interplay of all the different components you want as many tests as possible, OOM is possible, but you could simply limit the number of threads by setting `OMP_NUM_THREADS=1` which should give you something close to `sopt`

**Comment by ltalirz** [comment]
@dev-zero The regtest complains when setting `OMP_NUM_THREADS=1` (also exported)

It looks like the setting does not propagate to the place it's supposed to
```

ERROR: maxtasks should be greater or equal numprocs*OMP_NUM_THREADS
       maxtasks        = 1
       numprocs        = 1
       OMP_NUM_THREADS = 2
```

**Comment by dev-zero** [comment]
ok, interesting, likely something we have to change, regtests used to work with `sopt`, hence they should work with `psmp` and `OMP_NUM_THREADS=1`.
But since `numprocs = 1` I doubt that the OMP runtime will spawn too many threads itself to cause an OOM, so there is likely something else at play still.

**Comment by oschuett** [comment]
Try:

```
make test ARCH=${ARCH} VERSION=${VERSION} TESTOPTS="-ompthreads 1"
```

**Comment by ltalirz** [comment]
Thanks, Ole - I think the issue was the mixture between the threads (?) used by `make -j2 tests` and then the openmp threads inside the executable.
I've simply removed the `-j2` and now let cp2k use threads if it likes - it's anyhow better if that is tested.

From my side, I'm done.
I'm not building a separate .sopt executable here, but I create a symlink for backwards compatibility - hope that works.

**Review by jan-janssen — APPROVED** [review]
Great, thanks a lot @ltalirz - from my perspective this is ready to merge.

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
Same here, let's merge

**Pull request merged**
