### PR TITLE
add openmpi dependency

### PR DESCRIPTION
**Pull request by ltalirz**
let's see what environment variables this brings

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@jan-janssen I'm trying to add openmpi via the `conda_build_config.yaml` here but I'm getting
```
Error: Failed to render jinja template in /home/conda/recipe_root/meta.yaml:
'build' is undefined
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=257377&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=403

any ideas?

**Comment by ltalirz** [comment]
@dev-zero I'm setting `OMP_NUM_THREADS=1` when running the test suite, which did work fine for the OpenMP-only build.

In this PR I'm now trying to create a hybrid OpenMP-MPI build, and [am getting]((https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=260750&view=logs&j=656edd35-69):
```
ERROR: maxtasks should be greater or equal numprocs*OMP_NUM_THREADS
      maxtasks        = 1
       numprocs        = 2
       OMP_NUM_THREADS = 2
```
Is it possible that `make regtest` calls mpirun but somehow does not forward the environment variables?
Any ideas of what to do here?

**Comment by dev-zero** [comment]
> @dev-zero I'm setting `OMP_NUM_THREADS=1` when running the test suite, which did work fine for the OpenMP-only build.
> 
> In this PR I'm now trying to create a hybrid OpenMP-MPI build, and [am getting]((https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=260750&view=logs&j=656edd35-69):
> 
> ```
> ERROR: maxtasks should be greater or equal numprocs*OMP_NUM_THREADS
>       maxtasks        = 1
>        numprocs        = 2
>        OMP_NUM_THREADS = 2
> ```
> 
> Is it possible that `make regtest` calls mpirun but somehow does not forward the environment variables?
> Any ideas of what to do here?

it seems that `tools/regtesting/do_regtest` always overrides `OMP_NUM_THREADS`: 
https://github.com/cp2k/cp2k/blob/dc262fe48654f8fc6bc86ab0c8a84913c97842ae/tools/regtesting/do_regtest#L229-L235

Hence you should call it as `./tools/regtesting/do_regtest -ompthreads 1 ...`, or when running via `make ... test`: `make ... TESTOPTS="-ompthreads 1" test`.

**Comment by ltalirz** [comment]
Thanks for the hint @dev-zero! 

I've run into another issue with running the mpi version - in the test suite I'm getting the error
```
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh
```

I read [here](https://github.com/open-mpi/ompi/issues/1838#issuecomment-230077952) that one can fix this by passing `-mca plm isolated` to openmpi and I tried adding it to the `TESTOPTS` but that didn't seem to work.

Thinking more about this, however, it would anyhow have to be fixed in the openmpi dependency since we don't want people to have to always add this when running the code. @jan-janssen have you encountered this before in the MPI version of other conda recipes?

**Comment by dev-zero** [comment]
@ltalirz overriding the `mpiexec` command with `TESTOPTS="-mpiexec 'mpiexec --bind-to none -mca plm isolated'"` should do the job (probably needs some quotation mark escaping). Check with `ompi_info | grep "MCA plm"` whether the `ioslated` module is available (maybe it can be disabled within OpenMPIs modular system):

```console
$ ompi_info | grep "MCA plm"
                 MCA plm: isolated (MCA v2.1.0, API v2.0.0, Component v4.0.5)
                 MCA plm: rsh (MCA v2.1.0, API v2.0.0, Component v4.0.5)
```

If the option passing gets too cumbersome, I'd probably start calling `do_regtest` explicitly instead of going through `make`:

```console
mkdir -p regtesting/${ARCH}/${VERSION}
cd regtesting/${ARCH}/${VERSION}
../../../tools/regtesting/do_regtest -quick -arch ${ARCH} -version ${VERSION| -cp2kdir ../../../ -mpiexec "mpiexec --bind-to none -mca plm isolated"
```
Note: `-quick` will call `make` again, if you already have built it in a separate step (as I would do for easier debugging), you can use `-nobuild` to make the regtest script not try to build at all and simply run the tests.

If you have control over the Docker image, installing `ssh` might be the better solution, though.

**Comment by ltalirz** [comment]
Thanks @dev-zero ! Let's see whether the magic works ;-)

> If you have control over the Docker image, installing `ssh` might be the better solution, though.

Well, we might be able to install it as a dependency of cp2k, but that would seem rather weird ;-)
Is it really the norm that openmpi goes through SSH for calculations that run on one node?

**Comment by dev-zero** [comment]
> Thanks @dev-zero ! Let's see whether the magic works ;-)
> 
> > If you have control over the Docker image, installing `ssh` might be the better solution, though.
> 
> Well, we might be able to install it as a dependency of cp2k, but that would seem rather weird ;-)
> Is it really the norm that openmpi goes through SSH for calculations that run on one node?

My guess is that it checks for the path but doesn't use it when running on only one host. At least on my host I am able to `mpirun /bin/true` without a running `sshd`.

**Comment by ltalirz** [comment]
```
mpiexec: Error: unknown option "--bind-to-none"
```
Is this needed?

Edit: (my) Mistake detected :-D

**Comment by ltalirz** [comment]
@conda-forge admin, please rerender

Sorry for the typo!

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@dev-zero For the mpi executable, [90 tests failed and 14 are wrong](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=262118&view=logs&j=bc0b25a1-0ea6-5be3-17ad-1212c4b469de&t=578628e4-10f7-5e57-f7f0-bcdd728dd32a&l=28740)

```
Number of FAILED  tests 90
Number of WRONG   tests 14
Number of CORRECT tests 2685
Number of NEW     tests 0
Total number of   tests 2789
GREPME 90 14 2685 0 2789 X
```
The number of 90 seems to be reproducible; I saw it in one of the earlier tests. Of course it might have to do with memory... the wrong tests are a bit more worrying.

For comparison, with the openmp version built in parallel, [all 2789 tests pass](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=262118&view=logs&j=cc7f06b8-47bb-5f80-5e0d-1224ea213530&t=1c90cc3e-b00e-5eab-82a4-21c378b43900&l=10156).
What do we do here?

@jan-janssen The osx mpi build seems to be completely stuck with not even any output. Any ideas?

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
The results seem a bit random - now the test suite was aborted on the linux runner before it even finished

On the Mac OS runner, the test suite ran through, with a couple of failed results:
```
--------------------------------- Summary --------------------------------
Number of FAILED  tests 252
Number of WRONG   tests 15
Number of CORRECT tests 2540
Number of NEW     tests 1
Total number of   tests 2808
GREPME 252 15 2540 1 2808 X

Summary: correct: 2540 / 2808; new: 1; wrong: 15; failed: 252; 119min
Status: FAILED
```
What is failing seems a bit random
```
    ch2o.inp                                                   -7.84456570296343     OK (   0.56 sec) 
    ch2o_geo.inp                                               -7.84652942485170         RUNTIME FAIL 
    ch2o_lsd.inp                                               -7.19650182424153     OK (   0.92 sec) 
    ch2o_smear.inp                                             -7.19650182356748         RUNTIME FAIL 
    tmol.inp                                                  -41.90853885813244     OK (   0.46 sec) 
    h2.inp                                                     -1.03458111733093         RUNTIME FAIL 
    h2o-md.inp                                               -185.14802701318192         RUNTIME FAIL 
    h2o_str.inp                                                -5.76547414127219         RUNTIME FAIL 
    h2o-atprop.inp                                           -185.16704903931222     OK (   7.57 sec) 
    h2o-atprop0.inp                                          -187.45499307089054     OK (   1.14 sec) 
    si_geo.inp                                                -14.55678348854956     OK (   1.44 sec) 
    si_kp.inp                                                 -14.75431646498811     OK (  19.65 sec) 
    h2o_dimer.inp                                             -11.54506384037682         RUNTIME FAIL 
```

It's not clear to me how to continue with the mpi build 
@jan-janssen do you spot any potential issues?
I guess some of the other recipes you created also run test suites for the MPI executables, right?

**Comment by ltalirz** [comment]
@dev-zero @oschuett @jan-janssen 
As [mentioned previously](https://github.com/conda-forge/cp2k-feedstock/pull/10#issuecomment-753011343), adding an MPI executable might also fix the issue with the cp2k 8.1 PR.

The status quo here:
 * building the MPI versions works
 * but: the test suite has both failed and wrong test results
    * linux: 90 failed, 14 wrong
    * macos: 252 failed, 15 wrong
 * apparently, the test suite run can crash entirely, as happened with the linux run at the last commit (it was working before)

As you can see from the excerpt of the test suite output [above](https://github.com/conda-forge/cp2k-feedstock/pull/11#issuecomment-774026503), the runtime failures on macos seem rather random - I'm not able to see a pattern in which calculations work and which fail.

I'm already limiting the openmp threads to 1 for the mpi executable - I guess I could also limit the mpi threads to one but then I'm not really testing the mpi communication anymore.

Any ideas on how to proceed here?

**Comment by ltalirz** [comment]
@conda-forge-admin , please rerender

**Comment by ltalirz** [comment]
In the latest MPI build, we now have the following (see links for more details on the tests that failed):

[OSX](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=301295&view=logs&j=f781b17d-3cc8-5223-204f-29a64ca9ef56&t=4545a821-75b7-516c-9203-a809cfd0e138&l=30655)
```
Number of FAILED  tests 223
Number of WRONG   tests 28
Number of CORRECT tests 2556
Number of NEW     tests 1
Total number of   tests 2808
```

[linux](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=301295&view=logs&j=bc0b25a1-0ea6-5be3-17ad-1212c4b469de&t=578628e4-10f7-5e57-f7f0-bcdd728dd32a&l=15917)
```
Number of FAILED  tests 93
Number of WRONG   tests 15
Number of CORRECT tests 2699
Number of NEW     tests 1
Total number of   tests 2808

```

P.S. here are also the results for the nompi (OpenMP) build:
[osx](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=301295&view=logs&j=65769002-1136-5bbb-5e91-b3fbb7cdd70e&t=fdb86174-6733-5ed6-1dd5-f2594c29f582&l=7622)
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2805
Number of NEW     tests 3
Total number of   tests 2808
```

[linux](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=301295&view=logs&j=cc7f06b8-47bb-5f80-5e0d-1224ea213530&t=1c90cc3e-b00e-5eab-82a4-21c378b43900&l=6249)
```
Number of FAILED  tests 0
Number of WRONG   tests 1
Number of CORRECT tests 2804
Number of NEW     tests 3
Total number of   tests 2808
```

Hm... is it expected that the total number of tests are the same between mpi and no-mpi builds?

**Comment by ltalirz** [comment]
(Only) on the OSX build I'm seeing a couple of errors of the form
```
 Trying to move water_3_fdbg_inv-RESTART.wfn.bak-2 to water_3_fdbg_inv-RESTART.wfn.bak-3.
 rename returned status:           -1
 Problem moving file
```
Any ideas where this might come from?
Does that perhaps mean that the executable is not properly running with MPI but running multiple single-rank copies?

Edit: Seems to have surfaced a long time ago [here](https://lists.cp2k.org/archives/cp2k-user/2014-June/005423.html).

**Comment by ltalirz** [comment]
Finally getting closer:

Linux nompi
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2805
Number of NEW     tests 3
Total number of   tests 2808
```

Linux openmpi
```
Number of FAILED  tests 0
Number of WRONG   tests 1
Number of CORRECT tests 2850
Number of NEW     tests 8
Total number of   tests 2859
```

osx nompi
```
Number of FAILED  tests 0
Number of WRONG   tests 0
Number of CORRECT tests 2805
Number of NEW     tests 3
Total number of   tests 2808
```

osx openmpi
```
Number of FAILED  tests 101
Number of WRONG   tests 0
Number of CORRECT tests 2750
Number of NEW     tests 8
Total number of   tests 2859
```

Most of the runtime failures on osx openmpi seem to be related to invalid memory access (see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=301883&view=logs&j=f781b17d-3cc8-5223-204f-29a64ca9ef56&t=4545a821-75b7-516c-9203-a809cfd0e138&l=8891) )
```
 ----------------------------------- OT ---------------------------------------

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:
```

I didn't notice any specific compilation warnings. Any ideas where this might come from?

P.S. The one WRONG test on linux openmpi is
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$SRC_DIR/regtesting/Linux-x86-64-conda/psmp/TEST-Linux-x86-64-conda-psmp-2021-04-10_00-53-03/QS/regtest-rel/h2o-4.inp.out : 
 Total energy: : ref = -75.95928403905509 new = -75.95928404148025  
 relative error :   3.19270178e-11 >  numerical tolerance = 3e-11  
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Perhaps the tolerance should be adjusted here?
Edit: Ok, I see this [already happened](https://github.com/cp2k/cp2k/commit/a26a1975575fc6dc0bf926fbf2640ba91585f94a#diff-6eb3ef777bfa43bb0f9a87f7f2a480694b35482c4751c85095d18359f2c47f79)

**Comment by ltalirz** [comment]
Since I have no leads to go on, I'm closing this in favor of https://github.com/conda-forge/cp2k-feedstock/pull/21 that just adds the linux MPI build.

We can enable the osx MPI build lateron.

**Pull request closed without merging**
