### PR TITLE
2024.1

### PR DESCRIPTION
**Pull request by timostrunk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timostrunk** [comment]
I reenabled mkl-openmpi again to see if the segfault is gone. Also libxsmm is on for this test.

**Comment by timostrunk** [comment]
@oschuett 
2024.1 does not work with BUILD_DBCSR=ON anymore
cmake results in the following error:
```
CMake Error at CMakeLists.txt:594 (find_package):
  By not providing "FindDBCSR.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "DBCSR", but
  CMake did not find one.

  Could not find a package configuration file provided by "DBCSR" (requested
  version 2.6) with any of the following names:

    DBCSRConfig.cmake
    dbcsr-config.cmake

  Add the installation prefix of "DBCSR" to CMAKE_PREFIX_PATH or set
  "DBCSR_DIR" to a directory containing one of the above files.  If "DBCSR"
  provides a separate development package or SDK, be sure it has been
  installed.

```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=852134&view=logs&j=9e75aa61-5b36-561b-5f10-ea64a909c89f&t=6f1dc2fb-a6cb-5c46-0a92-93ce551ee674
Any pointers? Do we need another dbcsr release, too, maybe?

**Comment by timostrunk** [comment]
I think the cause is quite clear:
```
2023.2 searched like this for dbcsr:
f(NOT CP2K_BUILD_DBCSR)
  find_package(DBCSR 2.4 REQUIRED)
else()
```
2024.1 misses the NO CP2K_BUILD_DBCSR if

**Comment by timostrunk** [comment]
> 2024.1 misses the NO CP2K_BUILD_DBCSR if
@oschuett How should we continue here? Will you do a quick patch release or should I patch the source in the build in the feedstock?

**Comment by oschuett** [comment]
Yes, the CMake option `CP2K_BUILD_DBCSR` was dropped. Sorry, that was missing from the release notes.

For the time being we're still including the DBCSR sources in the our release tar-ball, but that's probably going to change with the next release as well. So the best solution forward would be to create a separate feedstock for DBCSR. The Spack project already took [that route](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dbcsr/package.py).

As a starting point we could use [this script](https://github.com/cp2k/cp2k/blob/master/tools/docker/scripts/install_dbcsr.sh).

**Comment by timostrunk** [comment]
Sure thing, if you setup the empty repository, I will create a PR. Until then I will try to push for 2023.2 still. I'm nearly converged on the libint feedstock. Once I add libint, we can merge that one, so that I can unblock my colleague.

**Comment by oschuett** [comment]
>Sure thing, if you setup the empty repository, I will create a PR. 

Yes, I can get the ball rolling unless @alazzaro would like to take the lead in packaging DBCSR for Conda?

**Comment by timostrunk** [comment]
For the moment I made the dbcsr build part of this recipe again.

**Comment by timostrunk** [comment]
Both 2023.2 and 2024.1 are now good to merge. 
Both have the incompatibility with scalapack-mkl, which is why I disabled that build again. Once we externalize dbcsr, we can pull out the dbcsr build from this recipe and rebuild.
But apart from that: Please review.

**Comment by oschuett** [comment]
> For the moment I made the dbcsr build part of this recipe again.

Perfect! Then we can take our time with the DBCSR package.

> Both 2023.2 and 2024.1 are now good to merge.

Thanks! I've already merged 2023.2, which created some conflicts for this PR...

**Comment by timostrunk** [comment]
Awesome, thanks! I will resolve them now. The builds for 2023.2 are still running anyways.

**Comment by timostrunk** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
