### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@oschuett This is simply a rebuild of cp2k 8.1 without any changes, other than perhaps some newer compiler version (here: gfortran 9.4.0).

The reason this build fails is:
```
mpifort -c -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cp2k-8.2.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -I $PREFIX/include -I $PREFIX/include/sirius -fbacktrace -ffree-form -fimplicit-none -std=f2008 -fopenmp -D__FFTW3 -D__LIBXSMM -D__parallel -D__SCALAPACK -D__SPGLIB -D__LIBXC -D__SIRIUS -D__COMPILE_ARCH="\"Linux-x86-64-conda\"" -D__COMPILE_DATE="\"Fri Dec 10 20:56:24 UTC 2021\"" -D__COMPILE_HOST="\"9fdca2a9cbab\"" -D__COMPILE_REVISION="\"git:310b7ab\"" -D__DATA_DIR="\"$SRC_DIR/data\"" -D__SHORT_FILE__="\"constraint_4x6.F\"" -I'$SRC_DIR/src/' -I'$SRC_DIR/obj/Linux-x86-64-conda/psmp/exts/dbcsr' constraint_4x6.F90 
/home/conda/feedstock_root/build_artifacts/cp2k_1639169135515/work/src/sirius_interface.F:542:90:

  542 |                      CALL sirius_option_set_logical(sctx, section_name, option_name, 1, 0)
      |                                                                                          1
Error: Type mismatch in argument 'default_values' at (1); passed INTEGER(4) to LOGICAL(4)
/home/conda/feedstock_root/build_artifacts/cp2k_1639169135515/work/src/sirius_interface.F:544:90:

  544 |                      CALL sirius_option_set_logical(sctx, section_name, option_name, 0, 0)
      |                                                                                          1
Error: Type mismatch in argument 'default_values' at (1); passed INTEGER(4) to LOGICAL(4)
/home/conda/feedstock_root/build_artifacts/cp2k_1639169135515/work/src/sirius_interface.F:556:100:

  556 |                   CALL sirius_option_set_logical(sctx, section_name, option_name, lvalsi(1), length)
      |                                                                                                    1
Error: Type mismatch in argument 'default_values' at (1); passed INTEGER(4) to LOGICAL(4)
```

Should this be fixed in cp2k?

P.S. Perhaps we can add a compiler flag to ignore this error for the time being? It doesn't seem like a big deal to convert int to bool here.

**Comment by ltalirz** [comment]
@jan-janssen Perhaps try appending `-fallow-argument-mismatch` to the `FCFLAGS` (+ a comment to remove it again when it is no longer needed)

**Comment by ltalirz** [comment]
Hm... apparently this flag was only introduced with gfortran 10.
It's still not clear to me why gfortran 9 is warning about it, and how to turn the warning off.

**Pull request closed without merging**
