### PR TITLE
[on hold] reenable osx

### LINKED ISSUE #22: re-enable osx build
The Arch file for the OSX MPI build has already been added but it is currrently disabled due to test failures, see https://github.com/conda-forge/cp2k-feedstock/pull/11#issuecomment-817101976

```
Number of FAILED  tests 101
Number of WRONG   tests 0
Number of CORRECT tests 2750
Number of NEW     tests 8
Total number of   tests 2859
```

Most of the runtime failures on osx openmpi seem to be related to invalid memory access (see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=301883&view=logs&j=f781b17d-3cc8-5223-204f-29a64ca9ef56&t=4545a821-75b7-516c-9203-a809cfd0e138&l=8891) )
```
 ----------------------------------- OT ---------------------------------------

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:
```

I'd appreciate some help with this

P.S. We may want to revert disabling the `-framework Accelerate` from https://github.com/conda-forge/cp2k-feedstock/pull/11/commits/488a59443ab4a7326f95df2b67743883420ca62b which was just a test.

### PR DESCRIPTION
**Pull request by ltalirz**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ltalirz** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
libxc 5.1 does not provide fortran bindings on osx https://github.com/conda-forge/libxc-feedstock/issues/15

**Comment by oschuett** [comment]
This PR is rather old. Should we close it?

For what it's worth, we are actually supporting macOS officially now:
https://www.cp2k.org/howto:compile_on_macos
https://dashboard.cp2k.org/archive/darwin-gnu-arm64-psmp/index.html

**Comment by ltalirz** [comment]
sure, let's close. I'll copy your comment into the issue

**Pull request closed without merging**
